//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 10:01:09 AM CEST 
//


package nothing;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for marshal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="marshal">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reservation" type="{}rsiReservation" minOccurs="0"/>
 *         &lt;element name="seat" type="{}rsiSeat" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "marshal", propOrder = {
    "reservation",
    "seat"
})
public class Marshal {

    protected RsiReservation reservation;
    protected RsiSeat seat;

    /**
     * Gets the value of the reservation property.
     * 
     * @return
     *     possible object is
     *     {@link RsiReservation }
     *     
     */
    public RsiReservation getReservation() {
        return reservation;
    }

    /**
     * Sets the value of the reservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link RsiReservation }
     *     
     */
    public void setReservation(RsiReservation value) {
        this.reservation = value;
    }

    /**
     * Gets the value of the seat property.
     * 
     * @return
     *     possible object is
     *     {@link RsiSeat }
     *     
     */
    public RsiSeat getSeat() {
        return seat;
    }

    /**
     * Sets the value of the seat property.
     * 
     * @param value
     *     allowed object is
     *     {@link RsiSeat }
     *     
     */
    public void setSeat(RsiSeat value) {
        this.seat = value;
    }

}
