//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 10:01:09 AM CEST 
//


package nothing;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nothing package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
class ObjectFactory {

    private final static QName _RsiScreening_QNAME = new QName("", "rsiScreening");
    private final static QName _RsiSeatReserved_QNAME = new QName("", "rsiSeatReserved");
    private final static QName _RsiClient_QNAME = new QName("", "rsiClient");
    private final static QName _Marshal_QNAME = new QName("", "marshal");
    private final static QName _RsiMovie_QNAME = new QName("", "rsiMovie");
    private final static QName _ResponseList_QNAME = new QName("", "responseList");
    private final static QName _RsiAuditorium_QNAME = new QName("", "rsiAuditorium");
    private final static QName _RsiReservation_QNAME = new QName("", "rsiReservation");
    private final static QName _RsiSeat_QNAME = new QName("", "rsiSeat");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nothing
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RsiScreening }
     * 
     */
    public RsiScreening createRsiScreening() {
        return new RsiScreening();
    }

    /**
     * Create an instance of {@link RsiSeatReserved }
     * 
     */
    public RsiSeatReserved createRsiSeatReserved() {
        return new RsiSeatReserved();
    }

    /**
     * Create an instance of {@link RsiClient }
     * 
     */
    public RsiClient createRsiClient() {
        return new RsiClient();
    }

    /**
     * Create an instance of {@link Marshal }
     * 
     */
    public Marshal createMarshal() {
        return new Marshal();
    }

    /**
     * Create an instance of {@link RsiMovie }
     * 
     */
    public RsiMovie createRsiMovie() {
        return new RsiMovie();
    }

    /**
     * Create an instance of {@link ResponseList }
     * 
     */
    public ResponseList createResponseList() {
        return new ResponseList();
    }

    /**
     * Create an instance of {@link RsiAuditorium }
     * 
     */
    public RsiAuditorium createRsiAuditorium() {
        return new RsiAuditorium();
    }

    /**
     * Create an instance of {@link RsiReservation }
     * 
     */
    public RsiReservation createRsiReservation() {
        return new RsiReservation();
    }

    /**
     * Create an instance of {@link RsiSeat }
     * 
     */
    public RsiSeat createRsiSeat() {
        return new RsiSeat();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RsiScreening }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rsiScreening")
    public JAXBElement<RsiScreening> createRsiScreening(RsiScreening value) {
        return new JAXBElement<RsiScreening>(_RsiScreening_QNAME, RsiScreening.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RsiSeatReserved }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rsiSeatReserved")
    public JAXBElement<RsiSeatReserved> createRsiSeatReserved(RsiSeatReserved value) {
        return new JAXBElement<RsiSeatReserved>(_RsiSeatReserved_QNAME, RsiSeatReserved.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RsiClient }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rsiClient")
    public JAXBElement<RsiClient> createRsiClient(RsiClient value) {
        return new JAXBElement<RsiClient>(_RsiClient_QNAME, RsiClient.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Marshal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "marshal")
    public JAXBElement<Marshal> createMarshal(Marshal value) {
        return new JAXBElement<Marshal>(_Marshal_QNAME, Marshal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RsiMovie }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rsiMovie")
    public JAXBElement<RsiMovie> createRsiMovie(RsiMovie value) {
        return new JAXBElement<RsiMovie>(_RsiMovie_QNAME, RsiMovie.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "responseList")
    public JAXBElement<ResponseList> createResponseList(ResponseList value) {
        return new JAXBElement<ResponseList>(_ResponseList_QNAME, ResponseList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RsiAuditorium }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rsiAuditorium")
    public JAXBElement<RsiAuditorium> createRsiAuditorium(RsiAuditorium value) {
        return new JAXBElement<RsiAuditorium>(_RsiAuditorium_QNAME, RsiAuditorium.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RsiReservation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rsiReservation")
    public JAXBElement<RsiReservation> createRsiReservation(RsiReservation value) {
        return new JAXBElement<RsiReservation>(_RsiReservation_QNAME, RsiReservation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RsiSeat }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rsiSeat")
    public JAXBElement<RsiSeat> createRsiSeat(RsiSeat value) {
        return new JAXBElement<RsiSeat>(_RsiSeat_QNAME, RsiSeat.class, null, value);
    }

}
