//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 10:01:09 AM CEST 
//


package nothing;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for responseList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="responseList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="auditoriums" type="{}rsiAuditorium" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="clients" type="{}rsiClient" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="movies" type="{}rsiMovie" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reservations" type="{}rsiReservation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="screenings" type="{}rsiScreening" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="seats" type="{}rsiSeat" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reservedseats" type="{}rsiSeatReserved" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "responseList", propOrder = {
    "auditoriums",
    "clients",
    "movies",
    "reservations",
    "screenings",
    "seats",
    "reservedseats"
})
public class ResponseList {

    protected List<RsiAuditorium> auditoriums;
    protected List<RsiClient> clients;
    protected List<RsiMovie> movies;
    protected List<RsiReservation> reservations;
    protected List<RsiScreening> screenings;
    protected List<RsiSeat> seats;
    protected List<RsiSeatReserved> reservedseats;

    /**
     * Gets the value of the auditoriums property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the auditoriums property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuditoriums().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RsiAuditorium }
     * 
     * 
     */
    public List<RsiAuditorium> getAuditoriums() {
        if (auditoriums == null) {
            auditoriums = new ArrayList<RsiAuditorium>();
        }
        return this.auditoriums;
    }

    /**
     * Gets the value of the clients property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clients property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClients().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RsiClient }
     * 
     * 
     */
    public List<RsiClient> getClients() {
        if (clients == null) {
            clients = new ArrayList<RsiClient>();
        }
        return this.clients;
    }

    /**
     * Gets the value of the movies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the movies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMovies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RsiMovie }
     * 
     * 
     */
    public List<RsiMovie> getMovies() {
        if (movies == null) {
            movies = new ArrayList<RsiMovie>();
        }
        return this.movies;
    }

    /**
     * Gets the value of the reservations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reservations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReservations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RsiReservation }
     * 
     * 
     */
    public List<RsiReservation> getReservations() {
        if (reservations == null) {
            reservations = new ArrayList<RsiReservation>();
        }
        return this.reservations;
    }

    /**
     * Gets the value of the screenings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the screenings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScreenings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RsiScreening }
     * 
     * 
     */
    public List<RsiScreening> getScreenings() {
        if (screenings == null) {
            screenings = new ArrayList<RsiScreening>();
        }
        return this.screenings;
    }

    /**
     * Gets the value of the seats property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the seats property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSeats().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RsiSeat }
     * 
     * 
     */
    public List<RsiSeat> getSeats() {
        if (seats == null) {
            seats = new ArrayList<RsiSeat>();
        }
        return this.seats;
    }

    /**
     * Gets the value of the reservedseats property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reservedseats property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReservedseats().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RsiSeatReserved }
     * 
     * 
     */
    public List<RsiSeatReserved> getReservedseats() {
        if (reservedseats == null) {
            reservedseats = new ArrayList<RsiSeatReserved>();
        }
        return this.reservedseats;
    }

}
