//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.27 at 04:08:21 PM CEST 
//


package nothing;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.Date;


/**
 * <p>Java class for rsiScreening complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rsiScreening">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="auditoriumId" type="{}rsiAuditorium" minOccurs="0"/>
 *         &lt;element name="movieId" type="{}rsiMovie" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="screeningStart" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rsiScreening", propOrder = {
    "auditoriumId",
    "movieId",
    "id",
    "screeningStart"
})
public class RsiScreening {

    protected RsiAuditorium auditoriumId;
    protected RsiMovie movieId;
    protected Integer id;
    @XmlSchemaType(name = "dateTime")
    protected long screeningStart;

//    protected XMLGregorianCalendar xmlGregorianCalendar;
//
//    public XMLGregorianCalendar getXmlGregorianCalendar() {
//        return xmlGregorianCalendar;
//    }
//
//    public void setXmlGregorianCalendar() throws DatatypeConfigurationException {
//        Timestamp ts = new Timestamp(new Date().getTime());
//        ts.setTime(screeningStart);
//        LocalDateTime ldt = ts.toLocalDateTime();
//        XMLGregorianCalendar cal = DatatypeFactory.newInstance().newXMLGregorianCalendar();
//        cal.setYear(ldt.getYear());
//        cal.setMonth(ldt.getMonthValue());
//        cal.setDay(ldt.getDayOfMonth());
//        cal.setHour(ldt.getHour());
//        cal.setMinute(ldt.getMinute());
//        cal.setSecond(ldt.getSecond());
//        cal.setFractionalSecond(new BigDecimal("0." + ldt.getNano()));
//        this.xmlGregorianCalendar = cal;
//    }

    /**
     * Gets the value of the auditoriumId property.
     * 
     * @return
     *     possible object is
     *     {@link RsiAuditorium }
     *     
     */
    public RsiAuditorium getAuditoriumId() {
        return auditoriumId;
    }

    /**
     * Sets the value of the auditoriumId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RsiAuditorium }
     *     
     */
    public void setAuditoriumId(RsiAuditorium value) {
        this.auditoriumId = value;
    }

    /**
     * Gets the value of the movieId property.
     * 
     * @return
     *     possible object is
     *     {@link RsiMovie }
     *     
     */
    public RsiMovie getMovieId() {
        return movieId;
    }

    /**
     * Sets the value of the movieId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RsiMovie }
     *     
     */
    public void setMovieId(RsiMovie value) {
        this.movieId = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the screeningStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public long getScreeningStart() {
        return screeningStart;
    }

    /**
     * Sets the value of the screeningStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */

    public void setScreeningStart(long value){
        this.screeningStart=value;
    }
//    public void setScreeningStart(long value) throws DatatypeConfigurationException {
//        this.screeningStart=value;
//        Timestamp ts = new Timestamp(new Date().getTime());
//        ts.setTime(value);
//        LocalDateTime ldt = ts.toLocalDateTime();
//        XMLGregorianCalendar cal = DatatypeFactory.newInstance().newXMLGregorianCalendar();
//        cal.setYear(ldt.getYear());
//        cal.setMonth(ldt.getMonthValue());
//        cal.setDay(ldt.getDayOfMonth());
//        cal.setHour(ldt.getHour());
//        cal.setMinute(ldt.getMinute());
//        cal.setSecond(ldt.getSecond());
//        cal.setFractionalSecond(new BigDecimal("0." + ldt.getNano()));
//        System.out.println(ldt);
//        System.out.println(cal);
//        this.xmlGregorianCalendar=cal;
////        this.screeningStart = cal;
//    }

    public XMLGregorianCalendar getGregorianCalendar() throws DatatypeConfigurationException {
        Timestamp ts = new Timestamp(new Date().getTime());
        ts.setTime(this.screeningStart);
        LocalDateTime ldt = ts.toLocalDateTime();
        XMLGregorianCalendar cal = DatatypeFactory.newInstance().newXMLGregorianCalendar();
        cal.setYear(ldt.getYear());
        cal.setMonth(ldt.getMonthValue());
        cal.setDay(ldt.getDayOfMonth());
        cal.setHour(ldt.getHour());
        cal.setMinute(ldt.getMinute());
        cal.setSecond(ldt.getSecond());
        cal.setFractionalSecond(new BigDecimal("0." + ldt.getNano()));
        System.out.println(ldt);
        System.out.println(cal);
        return cal;
    }
}
